apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-test-deploy
  labels:
    app: final-test
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: final-test
  template:
    metadata:
      labels:
        app: final-test
    spec:
      containers:
      - name: final-test
        image: morandan7/flask-aws-monitor 
        ports:
        - containerPort: 5001