apiVersion: v1
kind: Service
metadata:
  name: final-test-service
spec:
  type: LoadBalancer  # lb type
  selector:
    app: final-test  
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 5001  
  
